site_name: Wenxuan Zhu

theme:
  name: 'material'

extra_javascript: 
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML

markdown_extensions:
    - mdx_math


nav:
  - Overview: index.md  
  - Curriculum vitae: cv.md
  - Blog: blog.md
  - Portfolio:
    - Object detection: armor_detect.md
    - Motion preditction: motion_predict.md
    - Motion fitting: rune.md