site_name: Wenxuan Zhu

theme:
  name: 'material'


nav:
  - Overview: index.md  
  - Curriculum vitae: cv.md
  - Study record: study_record.md
  - Blog: blog.md
  - Portfolio :
    # - Object detection: armor_detect.md
    # - Motion preditction: motion_predict.md
    # - Motion fitting: rune.md
    # - Modeling the rotated target and auto-shoot: anti_top.md
